version: 0.0
os: linux
files:
  - source: /
    destination: /opt/wdr/env/instand
hooks:
  BeforeInstall:
    - location: instand-ops/codedeploy/scripts/before_install.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: instand-ops/codedeploy/scripts/after_install.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: instand-ops/codedeploy/scripts/application_start.sh
      timeout: 300
      runas: root
